namespace:
  name: staging

replicaCount: 1

image:
  repository: nginx
  tag: 1.18.0
  pullPolicy: IfNotPresent

resources:
  request:
    cpu: 50m
    memory: 128Mi

configmap:
  data: "version: 1.17.0"
