namespace:
  name: prod

replicaCount: 2

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

resources:
  request:
    cpu: 70m
    memory: 256Mi

service:
  type: ClusterIP
  port: 80

configmap:
  data: "version: 1.18.0"
